const contractMetric = (key, placeholder) => ({
  key,
  placeholder,
  source: 'vault-contract',
});

const eulerEarnUrl = (vaultAddress, networkId) => `https://app.euler.finance/earn/${vaultAddress}?network=${networkId}`;
const eulerLendUrl = (vaultAddress, networkId) => `https://app.euler.finance/lend/${vaultAddress}?network=${networkId}`;
const eulerBorrowUrl = (collateralVaultAddress, debtVaultAddress, networkId) => (
  `https://app.euler.finance/borrow/${collateralVaultAddress}/${debtVaultAddress}?network=${networkId}`
);
const marketEulerLinks = ({ collateralVaultAddress, debtVaultAddress, networkId }) => ({
  borrow: eulerBorrowUrl(collateralVaultAddress, debtVaultAddress, networkId),
  collateral: eulerLendUrl(collateralVaultAddress, networkId),
  debt: eulerLendUrl(debtVaultAddress, networkId),
});

const ARBITRUM_CONTRACTS = {
  crvUsdToken: '0x498bf2b1e120fed3ad3d42ea2165e9b73f99c1e5',
  crvUsdOracle: '0xC24d58Df275eEeb3912A486dF990d6097E742161',
  asdCrvOracle: '0xE7e3b3d3cd1Ba20912f215B36F5F50951bB75e63',
  xEthOracle: '0x23Ee1171Ec73BbdAa7de7A0ADFBcAf3E382893Ec',
  eulerRouter: '0x6613bA15D293c64B5C8997A2131fFe311A4fCEd9',
  asdCrvIrm: '0x665eFf08Ff568D530604DC30250996dabf6d2413',
  xEthIrm: '0x723287ee5709297570Fb0ceB076712fc34A0459b',
  asdCrvCollateralVault: '0x2E93b06831301d0B6a3F0a7257cA0336fA717F02',
  xEthCollateralVault: '0xe3c721aD080EA841bda981B518ac21b66431C420',
  crvUsdAsdCrvMarketVault: '0xbea90e53c938d815F01cD46Ce493c5B66f2dB632',
  crvUsdXethMarketVault: '0xaCEe8EFF71a03d31076160C351d14B849768B4E1',
  crvUsdEarnVault: '0x0396784d22a631C608708AFB63dd4E40b56bFe78',
  liquidator: '0x081b0c3CBC1131c2f46DFfCfFBb27fC765008fC4',
};

const MAINNET_CONTRACTS = {
  crvUsdToken: '0xf939e0a03fb07f59a73314e73794be0e57ac1b4e',
  scrvUsdVault: '0x0655977feb2f289a4ab78af67bab0d17aab84367',
  iporCrvUsdVault: '0xE31Aa86e21e420d03E52AaA06C349BDC525a664F',
  scrvUsdOracle: '0x1654a1DEfb03D54F27Aa00D0236886514c59304c',
  asdCrvOracle: '0x1DBD7870c903F2c5676075aE2C9d49AF6A3B0486',
  aCrvOracle: '0x5FaD9B003BfDD943F159f45f6aE02F23d3387Af0',
  yvyCrvOracle: '0xBb63D22B5027Fcb3F8706502EF46305D745cd42b',
  yvCurveYbOracle: '0x03f65cA3e00a73A98abf10B520Aeb8232fB28E66',
  ybCrvUsdOracle: '0xC2120CD80a6393d3097c956cFCD1AF1656cb18D5',
  asdCrvIrm: '0x2eF9E0818Ca6923b6580C6cD817Ed38cD63fc739',
  aCrvIrm: '0x6a3B6480fC3A8E2ac3815A26b605b26b1abc6080',
  yvyCrvIrm: '0xDEc5332028c3C0289c8407C8D70813680229f341',
  yvCurveYbIrm: '0xa682D29C180F3Be1F59A01c568A6868F2Cf92af8',
  ybCrvUsdIrm: '0x0de0b5749833871b59907e47Be2a97e50373A0D4',
  asdCrvCollateralVault: '0x8df2B252D4d8D0e1E05d656f054329dDA0f2f1c6',
  asdCrvMarketVault: '0xe45C513dD473138d095221E0f923634F18795db0',
  aCrvCollateralVault: '0x006e2989B00f2bfe070502B1fE0F5Ae8a007e3a2',
  aCrvMarketVault: '0xa264e81dF3C81953eEbae182441811e5CE894632',
  yvyCrvCollateralVault: '0x6Ae345Ab8b8Bcf31949fF020670036D2184d2452',
  yvyCrvMarketVault: '0x5b1E4F55B71eeD2bdb283B630fcdC064fB69e8D0',
  yvCurveYbCollateralVault: '0x664B722629B4FAf39ed4e5152fb540A01BC0e006',
  yvCurveYbMarketVault: '0x64D3aF907DEb5E58b3300977977B6B134d4005Ec',
  ybCrvUsdCollateralVault: '0x8df8031519d47D09CdaC9F64e12277403753101f',
  ybCrvUsdMarketVault: '0xffBFC21fA9F3ee0B35B45F272fF83B315D5B5680',
  scrvUsdEarnVault: '0x719d2EF37CE4b66d0c2180ae4915C0F31bC0261e',
  liquidator: '0x57dC984127df2a9ea4C7bC5c2e40102097881295',
};

export const TOKEN_DESCRIPTIONS = {
  asdCRV: 'asdCRV is an auto-compounding Aladdin Concentrator vault token built around CRV-related yield strategies.',
  aCRV: 'aCRV represents a share of an auto-compounding Concentrator vault backed by cvxCRV staking strategy yield.',
  'st-yCRV': 'st-yCRV is staked yCRV, earning a share of Yearn veCRV revenue, optimized vote incentives, and boosted staking yield.',
  'yvCurve-yYB': 'yvCurve-yYB represents Yearn vault exposure to YieldBasis liquidity, packaging LP strategy yield into a vault token.',
  YBcrvUSD: 'YBcrvUSD represents YieldBasis crvUSD liquidity exposure designed to earn fees while the protocol manages leveraged LP debt.',
  scrvUSD: 'scrvUSD is Curve\'s yield-bearing crvUSD savings token, designed to accrue autocompounding interest from crvUSD system revenue.',
  crvUSD: 'crvUSD is Curve\'s decentralized, overcollateralized stablecoin protected by LLAMMA-style liquidation mechanics.',
  xETH: 'xETH is f(x) Protocol leveraged ETH, a composable long ETH token designed to provide ETH upside exposure without a funding rate.',
};

const marketSeeds = [
  {
    title: 'asdCRV/scrvUSD',
    collateral: 'asdCRV',
    collateralVaultAddress: MAINNET_CONTRACTS.asdCrvCollateralVault,
    debtVaultAddress: MAINNET_CONTRACTS.asdCrvMarketVault,
    collateralOracleAddress: MAINNET_CONTRACTS.asdCrvOracle,
    irmAddress: MAINNET_CONTRACTS.asdCrvIrm,
  },
  {
    title: 'aCRV/scrvUSD',
    collateral: 'aCRV',
    collateralVaultAddress: MAINNET_CONTRACTS.aCrvCollateralVault,
    debtVaultAddress: MAINNET_CONTRACTS.aCrvMarketVault,
    collateralOracleAddress: MAINNET_CONTRACTS.aCrvOracle,
    irmAddress: MAINNET_CONTRACTS.aCrvIrm,
  },
  {
    title: 'st-yCRV/scrvUSD',
    collateral: 'st-yCRV',
    collateralVaultAddress: MAINNET_CONTRACTS.yvyCrvCollateralVault,
    debtVaultAddress: MAINNET_CONTRACTS.yvyCrvMarketVault,
    collateralOracleAddress: MAINNET_CONTRACTS.yvyCrvOracle,
    irmAddress: MAINNET_CONTRACTS.yvyCrvIrm,
  },
  {
    title: 'yvCurve-yYB/scrvUSD',
    collateral: 'yvCurve-yYB',
    collateralVaultAddress: MAINNET_CONTRACTS.yvCurveYbCollateralVault,
    debtVaultAddress: MAINNET_CONTRACTS.yvCurveYbMarketVault,
    collateralOracleAddress: MAINNET_CONTRACTS.yvCurveYbOracle,
    irmAddress: MAINNET_CONTRACTS.yvCurveYbIrm,
  },
  {
    title: 'YBcrvUSD/scrvUSD',
    collateral: 'YBcrvUSD',
    collateralVaultAddress: MAINNET_CONTRACTS.ybCrvUsdCollateralVault,
    debtVaultAddress: MAINNET_CONTRACTS.ybCrvUsdMarketVault,
    collateralOracleAddress: MAINNET_CONTRACTS.ybCrvUsdOracle,
    irmAddress: MAINNET_CONTRACTS.ybCrvUsdIrm,
  },
];

const markets = marketSeeds.map((seed, index) => ({
  id: `market-${index + 1}`,
  type: 'market',
  chainId: 'ethereum',
  network: 'Ethereum Mainnet',
  contractAddress: seed.debtVaultAddress,
  abi: './public/abis/IEVault.json',
  collateralVaultAddress: seed.collateralVaultAddress,
  collateralVaultAbi: './public/abis/IEVault.json',
  debtVaultAddress: seed.debtVaultAddress,
  debtVaultAbi: './public/abis/IEVault.json',
  eulerLinks: marketEulerLinks({
    collateralVaultAddress: seed.collateralVaultAddress,
    debtVaultAddress: seed.debtVaultAddress,
    networkId: 1,
  }),
  collateralOracleAddress: seed.collateralOracleAddress,
  debtOracleAddress: MAINNET_CONTRACTS.scrvUsdOracle,
  oracleAddress: seed.collateralOracleAddress,
  irmAddress: seed.irmAddress,
  irmAbi: './public/abis/IRMLinearKink.json',
  navLabel: seed.title,
  title: seed.title,
  subtitle: 'CurveYield Markets',
  collateral: seed.collateral,
  debt: 'scrvUSD',
  supplyApy: '0.00%',
  borrowApy: '0.00%',
  netApy: '0.00%',
  maxRoe: '0.00%',
  multiplier: '1.00x',
  price: '$0.00',
  maxLtv: '0.00%',
  liquidationLtv: '0.00%',
  contractMetrics: [
    contractMetric('price', '$0.00'),
    contractMetric('supplyApy', '0.00%'),
    contractMetric('borrowApy', '0.00%'),
    contractMetric('netApy', '0.00%'),
    contractMetric('maxRoe', '0.00%'),
    contractMetric('maxLtv', '0.00%'),
    contractMetric('liquidationLtv', '0.00%'),
    contractMetric('maxMultiplier', '1.00x'),
  ],
}));

const exposureRows = markets
  .filter((market) => market.debt === 'scrvUSD')
  .map((market) => ({
    pageId: market.id,
    label: market.title,
    asset: market.collateral,
    apy: '0.00%',
    allocation: '$0.00',
    cap: 'Not configured',
    debtVaultAddress: market.debtVaultAddress || market.contractAddress,
  }));

const earnVault = {
  id: 'earn-scrvusd',
  type: 'earn',
  chainId: 'ethereum',
  network: 'Ethereum Mainnet',
  contractAddress: MAINNET_CONTRACTS.scrvUsdEarnVault,
  tokenAddress: MAINNET_CONTRACTS.scrvUsdVault,
  abi: './public/abis/IEulerEarn.json',
  underlyingAddress: MAINNET_CONTRACTS.crvUsdToken,
  priceAssetAddress: MAINNET_CONTRACTS.scrvUsdVault,
  oracleAddress: MAINNET_CONTRACTS.scrvUsdOracle,
  eulerLinks: {
    earn: eulerEarnUrl(MAINNET_CONTRACTS.scrvUsdEarnVault, 1),
  },
  navLabel: 'scrvUSD Earn',
  title: 'scrvUSD',
  subtitle: 'CurveYield Markets',
  asset: 'scrvUSD',
  logo: './assets/logos/scrvusd.png',
  supplyApy: '0.00%',
  price: '$0.00',
  performanceFee: '0.00%',
  allocator: 'CurveYield',
  vaultType: 'Managed',
  totalSupply: '$0.00',
  liquidity: '$0.00',
  exposures: exposureRows,
  contractMetrics: [
    contractMetric('price', '$0.00'),
    contractMetric('performanceFee', '0.00%'),
    contractMetric('totalSupply', '$0.00'),
    contractMetric('availableLiquidity', '$0.00'),
    contractMetric('supplyApy', '0.00%'),
    contractMetric('projectedEarnings', '0 scrvUSD ≈ $0'),
    contractMetric('walletBalance', '0 scrvUSD'),
  ],
};

const arbitrumCrvUsdEarnVault = {
  id: 'arb-earn-crvusd',
  type: 'earn',
  chainId: 'arbitrum',
  network: 'Arbitrum',
  contractAddress: ARBITRUM_CONTRACTS.crvUsdEarnVault,
  tokenAddress: ARBITRUM_CONTRACTS.crvUsdToken,
  abi: './public/abis/IEulerEarn.json',
  eulerLinks: {
    earn: eulerEarnUrl(ARBITRUM_CONTRACTS.crvUsdEarnVault, 42161),
  },
  oracleAddress: ARBITRUM_CONTRACTS.crvUsdOracle,
  oracleAbi: './public/abis/crvUSDtoUSDEulerOracle.json',
  navLabel: 'crvUSD Earn',
  title: 'crvUSD',
  subtitle: 'CurveYield Markets',
  asset: 'crvUSD',
  supplyApy: '0.00%',
  price: '$0.00',
  performanceFee: '0.00%',
  allocator: 'CurveYield',
  vaultType: 'Managed',
  totalSupply: '$0.00',
  liquidity: '$0.00',
  exposures: [],
  contractMetrics: [
    contractMetric('price', '$0.00'),
    contractMetric('performanceFee', '0.00%'),
    contractMetric('totalSupply', '$0.00'),
    contractMetric('availableLiquidity', '$0.00'),
    contractMetric('supplyApy', '0.00%'),
    contractMetric('projectedEarnings', '0 crvUSD ≈ $0'),
    contractMetric('walletBalance', '0 crvUSD'),
  ],
};

const arbitrumAsdCrvCrvUsdMarket = {
  id: 'arb-market-asdcrv-crvusd',
  type: 'market',
  chainId: 'arbitrum',
  network: 'Arbitrum',
  contractAddress: ARBITRUM_CONTRACTS.crvUsdAsdCrvMarketVault,
  abi: './public/abis/IEVault.json',
  collateralVaultAddress: ARBITRUM_CONTRACTS.asdCrvCollateralVault,
  collateralVaultAbi: './public/abis/IEVault.json',
  debtVaultAddress: ARBITRUM_CONTRACTS.crvUsdAsdCrvMarketVault,
  debtVaultAbi: './public/abis/IEVault.json',
  eulerLinks: marketEulerLinks({
    collateralVaultAddress: ARBITRUM_CONTRACTS.asdCrvCollateralVault,
    debtVaultAddress: ARBITRUM_CONTRACTS.crvUsdAsdCrvMarketVault,
    networkId: 42161,
  }),
  collateralOracleAddress: ARBITRUM_CONTRACTS.asdCrvOracle,
  collateralOracleAbi: './public/abis/ArbitrumAsdCRVtoUSDEulerOracle.json',
  debtOracleAddress: ARBITRUM_CONTRACTS.crvUsdOracle,
  debtOracleAbi: './public/abis/crvUSDtoUSDEulerOracle.json',
  routerAddress: ARBITRUM_CONTRACTS.eulerRouter,
  routerAbi: './public/abis/EulerRouter.json',
  irmAddress: ARBITRUM_CONTRACTS.asdCrvIrm,
  irmAbi: './public/abis/IRMLinearKink.json',
  navLabel: 'asdCRV/crvUSD',
  title: 'asdCRV/crvUSD',
  subtitle: 'CurveYield Markets',
  collateral: 'asdCRV',
  debt: 'crvUSD',
  supplyApy: '0.00%',
  borrowApy: '0.00%',
  netApy: '0.00%',
  maxRoe: '0.00%',
  multiplier: '1.00x',
  price: '$0.00',
  maxLtv: '0.00%',
  liquidationLtv: '0.00%',
  oracleAddress: ARBITRUM_CONTRACTS.eulerRouter,
  contractMetrics: [
    contractMetric('price', '$0.00'),
    contractMetric('supplyApy', '0.00%'),
    contractMetric('borrowApy', '0.00%'),
    contractMetric('netApy', '0.00%'),
    contractMetric('maxRoe', '0.00%'),
    contractMetric('maxLtv', '0.00%'),
    contractMetric('liquidationLtv', '0.00%'),
    contractMetric('maxMultiplier', '1.00x'),
  ],
};

const arbitrumXethCrvUsdMarket = {
  id: 'arb-market-xeth-crvusd',
  type: 'market',
  chainId: 'arbitrum',
  network: 'Arbitrum',
  contractAddress: ARBITRUM_CONTRACTS.crvUsdXethMarketVault,
  abi: './public/abis/IEVault.json',
  collateralVaultAddress: ARBITRUM_CONTRACTS.xEthCollateralVault,
  collateralVaultAbi: './public/abis/IEVault.json',
  debtVaultAddress: ARBITRUM_CONTRACTS.crvUsdXethMarketVault,
  debtVaultAbi: './public/abis/IEVault.json',
  eulerLinks: marketEulerLinks({
    collateralVaultAddress: ARBITRUM_CONTRACTS.xEthCollateralVault,
    debtVaultAddress: ARBITRUM_CONTRACTS.crvUsdXethMarketVault,
    networkId: 42161,
  }),
  collateralOracleAddress: ARBITRUM_CONTRACTS.xEthOracle,
  collateralOracleAbi: './public/abis/xETHtoUSDEulerOracle.json',
  debtOracleAddress: ARBITRUM_CONTRACTS.crvUsdOracle,
  debtOracleAbi: './public/abis/crvUSDtoUSDEulerOracle.json',
  routerAddress: ARBITRUM_CONTRACTS.eulerRouter,
  routerAbi: './public/abis/EulerRouter.json',
  irmAddress: ARBITRUM_CONTRACTS.xEthIrm,
  irmAbi: './public/abis/IRMLinearKink.json',
  navLabel: 'xETH/crvUSD',
  title: 'xETH/crvUSD',
  subtitle: 'CurveYield Markets',
  collateral: 'xETH',
  debt: 'crvUSD',
  supplyApy: '0.00%',
  borrowApy: '0.00%',
  netApy: '0.00%',
  maxRoe: '0.00%',
  multiplier: '1.00x',
  price: '$0.00',
  maxLtv: '0.00%',
  liquidationLtv: '0.00%',
  oracleAddress: ARBITRUM_CONTRACTS.eulerRouter,
  contractMetrics: [
    contractMetric('price', '$0.00'),
    contractMetric('supplyApy', '0.00%'),
    contractMetric('borrowApy', '0.00%'),
    contractMetric('netApy', '0.00%'),
    contractMetric('maxRoe', '0.00%'),
    contractMetric('maxLtv', '0.00%'),
    contractMetric('liquidationLtv', '0.00%'),
    contractMetric('maxMultiplier', '1.00x'),
  ],
};

const easyLiquidationsPage = {
  id: 'arb-easy-liquidations',
  type: 'liquidator',
  chainId: 'arbitrum',
  network: 'Arbitrum',
  contractAddress: ARBITRUM_CONTRACTS.liquidator,
  abi: './public/abis/ArbitrumEulerCollateralLiquidator.json',
  navLabel: 'Easy Liquidations',
  title: 'Easy Liquidations',
  subtitle: 'CurveYield Markets',
  headline: 'Easy Liquidation Contract',
  description: 'Earn liquidation fees without any up front costs or developer knowledge',
  upFrontCost: 'small gas charge, typically $0.02 - $0.08.',
  markets: [
    {
      label: 'asdCRV / crvUSD',
      marketNumber: 0,
      pageId: 'arb-market-asdcrv-crvusd',
    },
    {
      label: 'xETH / crvUSD',
      marketNumber: 1,
      pageId: 'arb-market-xeth-crvusd',
    },
  ],
  contractMetrics: [
    contractMetric('contract', ARBITRUM_CONTRACTS.liquidator),
  ],
};

const mainnetEasyLiquidationsPage = {
  id: 'eth-easy-liquidations',
  type: 'liquidator',
  chainId: 'ethereum',
  network: 'Ethereum Mainnet',
  contractAddress: MAINNET_CONTRACTS.liquidator,
  abi: './public/abis/EulerCollateralLiquidator.json',
  navLabel: 'Easy Liquidations',
  title: 'Easy Liquidations',
  subtitle: 'CurveYield Markets',
  headline: 'Easy Liquidation Contract',
  description: 'Earn liquidation fees without any up front costs or developer knowledge',
  upFrontCost: 'small gas charge, typically $0.02 - $0.08.',
  markets: [
    {
      label: 'asdCRV / scrvUSD',
      marketNumber: 0,
      pageId: 'market-1',
    },
    {
      label: 'aCRV / scrvUSD',
      marketNumber: 1,
      pageId: 'market-2',
    },
    {
      label: 'st-yCRV / scrvUSD',
      marketNumber: 2,
      pageId: 'market-3',
    },
    {
      label: 'yvCurve-yYB / scrvUSD',
      marketNumber: 3,
      pageId: 'market-4',
    },
    {
      label: 'YBcrvUSD / scrvUSD',
      marketNumber: 5,
      pageId: 'market-5',
    },
  ],
  contractMetrics: [
    contractMetric('contract', MAINNET_CONTRACTS.liquidator),
  ],
};

const homePage = {
  id: 'home',
  type: 'home',
  chainId: 'global',
  network: 'All chains',
  navLabel: 'Home',
  title: 'CurveYield',
  subtitle: 'CurveYield vaults and markets',
  contractMetrics: [],
};

const iporCrvUsdLpVault = {
  id: 'ipor-crvusd-lp-vault',
  type: 'ipor-vault',
  chainId: 'ethereum',
  network: 'Ethereum Mainnet',
  contractAddress: MAINNET_CONTRACTS.iporCrvUsdVault,
  abi: './public/abis/IEVault.json',
  navLabel: 'crvUSD LP Farming',
  title: 'CurveYield crvUSD',
  shareSymbol: 'cy-crvUSD',
  subtitle: 'StakeDAO OUSD/crvUSD LP Farming',
  asset: 'crvUSD',
  logo: './assets/logos/curveyield-512.png',
  externalUrl: 'https://app.ipor.io/fusion/ethereum/0xE31Aa86e21e420d03E52AaA06C349BDC525a664F/vault-info',
  sourceAprUrl: 'https://www.stakedao.org/',
  strategyName: 'Stake DAO OUSD/crvUSD Vault',
  poolName: 'Curve OUSD/crvUSD',
  yieldSources: [
    {
      id: 'stakedao-ousd-crvusd',
      kind: 'strategy',
      label: 'StakeDAO OUSD/crvUSD vault',
      project: 'stake-dao',
      chain: 'Ethereum',
      pool: 'aeb52bc8-2eb0-49d9-8571-28290c39a182',
    },
    {
      id: 'curve-ousd-crvusd',
      kind: 'curve-pool',
      label: 'Curve OUSD/crvUSD pool',
      project: 'curve-dex',
      chain: 'Ethereum',
      pool: '3811321b-c619-4c3b-bc69-3fe1f58391c6',
    },
  ],
  idleAssetName: 'Idle crvUSD',
  depositRoute: 'crvUSD -> Curve OUSD/crvUSD LP -> StakeDAO OUSD/crvUSD Vault',
  withdrawalLabel: 'Instant withdrawal with vault fee',
  feeLabel: 'Deposit fee 0.05% / withdrawal fee 0.20%',
  strategyApr: '0.00%',
  performanceHistory: {
    apy: [0, 0, 0, 0, 0, 0, 0],
    share: [1, 1, 1, 1, 1, 1, 1],
    apyMin: 0,
    apyMax: 1,
    shareMin: 1,
    shareMax: 1.01,
    apyLabels: ['1.00%', '0.50%', '0.00%'],
    shareLabels: ['1.010', '1.005', '1.000'],
  },
  allocationHistory: {
    labels: ['Idle crvUSD', 'Curve LP', 'StakeDAO vault'],
    values: [1, 0, 99],
    maxValueLabel: '100%',
    midValueLabel: '50%',
    minValueLabel: '0%',
  },
  totalValueManaged: '0.00',
  totalValueLocked: '0.00',
  contractMetrics: [
    contractMetric('totalSupply', '0.00'),
    contractMetric('totalAssets', '0.00'),
    contractMetric('availableLiquidity', '0.00'),
    contractMetric('supplyApy', '0.00%'),
    contractMetric('performanceApy', '0.00%'),
    contractMetric('walletBalance', '0 crvUSD'),
  ],
};

arbitrumCrvUsdEarnVault.exposures = [
  {
    label: arbitrumAsdCrvCrvUsdMarket.title,
    asset: arbitrumCrvUsdEarnVault.asset,
    caption: arbitrumAsdCrvCrvUsdMarket.collateral,
    apy: '0.00%',
    allocation: '$0.00',
    cap: 'Not configured',
    pageId: arbitrumAsdCrvCrvUsdMarket.id,
    debtVaultAddress: arbitrumAsdCrvCrvUsdMarket.debtVaultAddress || arbitrumAsdCrvCrvUsdMarket.contractAddress,
  },
  {
    label: arbitrumXethCrvUsdMarket.title,
    asset: arbitrumCrvUsdEarnVault.asset,
    caption: arbitrumXethCrvUsdMarket.collateral,
    apy: '0.00%',
    allocation: '$0.00',
    cap: 'Not configured',
    pageId: arbitrumXethCrvUsdMarket.id,
    debtVaultAddress: arbitrumXethCrvUsdMarket.debtVaultAddress || arbitrumXethCrvUsdMarket.contractAddress,
  },
];

export const DEFAULT_PAGE_ID = 'ipor-crvusd-lp-vault';

export const PAGES = [
  homePage,
  iporCrvUsdLpVault,
  ...markets,
  earnVault,
  arbitrumCrvUsdEarnVault,
  arbitrumAsdCrvCrvUsdMarket,
  arbitrumXethCrvUsdMarket,
  mainnetEasyLiquidationsPage,
  easyLiquidationsPage,
];

export function getPageById(id) {
  return PAGES.find((page) => page.id === id) || PAGES.find((page) => page.id === DEFAULT_PAGE_ID) || PAGES[0];
}

